### ISSUE TITLE
change groupId and package to org.apache.dubbo

### ISSUE THREAD

**Issue by diecui1202** [apache/incubator-dubbo-samples#31]

**Comment by diecui1202** [comment]
both master and samples-for-2.7.0-SNAPSHOT branches need to do.

**Comment by leyou240** [comment]
I would like to contribute.

**Comment by diecui1202** [comment]
@leyou240 I'm working on master. Could you do this job on samples-for-2.7.0-SNAPSHOT ?

**Comment by leyou240** [comment]
ok

**Comment by diecui1202** [comment]
cool.

**Comment by leyou240** [comment]
@diecui1202 #33 Have a check please!

**Comment by diecui1202** [comment]
@leyou240 I've merged your PR. Could u pls. take some time to add rat and checkstyle plugin on samples-for-2.7.0-SNAPSHOT? 

Master branch maybe is a good example.

**Comment by leyou240** [comment]
@diecui1202 hava a check #34 :)

**Comment by ralf0131** [comment]
This issue has been fixed.
