### ISSUE TITLE
IP clearance status

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo-samples#41]
| contributor                                          | commits | Lines changed        | contribution          | Employer | ASF ICLA signed? | Apache Dubbo Committer?| Contact                                             |
| --------------------------------------------------- | ------- | -------------------- | --------------------- | -------- | ---------------- | ---------------------- | --------------------------------------------------- |
| [nzomkxia](https://github.com/nzomkxia)             | 31      | 12,074 ++  657 --    | Too much              | Alibaba  | Yes              | Yes                    |                                                     |
| [beiwei30](https://github.com/beiwei30)             | 13      | 1,630 ++  162 --     | Too much              | Alibaba  | Yes              | Yes                    |                                                     |
| [diecui1202](https://github.com/diecui1202)         | 11      | 15,244 ++  13,566 -- | Too much              | Alibaba  | Yes              | Yes                    |                                                     |
| [satansk](https://github.com/satansk)               | 7       | 750 ++  86 --        | Scala sample          |          |      Yes          |      No      | [songkun.fp@gmail.com](mailto:songkun.fp@gmail.com) |
| [hengyunabc](https://github.com/hengyunabc)         | 6       | 2,694 ++  1,578 --   | hystrix sample        | Alibaba  |        Yes          |  No                      | [hengyunabc@gmail.com](mailto:hengyunabc@gmail.com) |
| [kimmking](https://github.com/kimmking)             | 5       | 537 ++  9 --         | Swagger rest sample   | Rongguan | Yes              | Yes                    |                                                     |
| [sinmaystar](https://github.com/sinmaystar)         | 4       | 439 ++  241 --       | Switch thread sample  |          |                  |                        | N/A                                                 |
| [lovepoem](https://github.com/lovepoem)             | 4       | 218 ++  3 --         | Travis support        | Weidian  | Yes              | Yes                    |                                                     |
| [ningyu1](https://github.com/ningyu1)               | 2       | 710 ++  79 --        | Multi registry sample |          | Yes              | No                     |                                                     |
| [ralf0131](https://github.com/ralf0131)             | 2       | 31 ++  19 --         | Docker sample         | Alibaba  | Yes              | Yes                    |                                                     |
| [sicw](https://github.com/sicw)                     | 1       | 20 ++  20 --         | Trivial               |          |                  |                        | N/A                                                 |
| [FicusWang](https://github.com/FicusWang)           | 1       | 185 ++  3 --         | Jetty sample          |          |                  |                        | N/A                                                 |
| [zijinoier](https://github.com/zijinoier)           | 1       | 539 ++  537 --       | Attachment sample     |          |                  |                        | [wenlc@zju.edu.cn](mailto:wenlc@zju.edu.cn)         |
| [shenlong123321](https://github.com/shenlong123321) | 1       | 1 ++  1 --           | Trivial               |          |                  |                        | [496933982@qq.com](mailto:496933982@qq.com)         |
| [Lxylona](https://github.com/Lxylona)               | 1       | 26 ++  26 --         | Translation           |          |                  |                        | N/A                                                 |
| [chickenlj](https://github.com/chickenlj)           | 1       | 3 ++  3 --           | Trivial               | Alibaba  | Yes              | Yes                    |                                                     |

**Comment by ralf0131** [comment]
@satansk @hengyunabc @sinmaystar @sicw @FicusWang @zijinoier @shenlong123321 @Lxylona 

Sorry to disturb you!

We are going to transfer dubbo-samples into ASF.  You have contributed to dubbo-samples[1] in the past, but never signed either Apache ICLA before. 

Since Dubbo has been donated to ASF, one required process is to ensure the intellectual property of each contribution of each subproject has been correctly transferred to ASF. 

To help dubbo-samples to finish the process, would you please help to sign the ICLA? You can follow this guide[1]. If you have any further questions, please drop me a message.

Thanks in advance!

[1] https://github.com/apache/incubator-dubbo/wiki/CLA-signing-guide

**Comment by satansk** [comment]
@ralf0131 I will sign it as quick as possible.

**Comment by ralf0131** [comment]
@satansk Thanks in advance!

**Comment by ralf0131** [comment]
Since the major contributor satansk and hengyunabc all signed ICLA, I think this issue can be closed.
