### ISSUE TITLE
So many unused files and some errors in config file

### ISSUE THREAD

**Issue by kexianjun** [apache/incubator-dubbo-samples#57]
I find that there are so many unused file and some error in config file,such as 
![image](https://user-images.githubusercontent.com/12162539/52843633-a905b380-313d-11e9-9a07-e4a8926cd2de.png)
![image](https://user-images.githubusercontent.com/12162539/52843647-af942b00-313d-11e9-8790-2847cfa9a552.png)
![image](https://user-images.githubusercontent.com/12162539/52843663-bc188380-313d-11e9-8d59-86f6d2e6defe.png)
![image](https://user-images.githubusercontent.com/12162539/52843673-c175ce00-313d-11e9-9a5f-ff57759b9638.png)
![image](https://user-images.githubusercontent.com/12162539/52843681-c76baf00-313d-11e9-8822-cae54b425154.png)
many modules has the same problem.

**Comment by lovepoem** [comment]
Please send a pr to delete the useless files

**Comment by kexianjun** [comment]
> Please send a pr to delete the useless files

ok, I'll fix it later.
