### ISSUE TITLE
dubbo-samples-async-original-future 模块的AsyncConsumer从RpcContext获取不到服务器写回的attachments

### ISSUE THREAD

**Issue by lizanle521** [apache/incubator-dubbo-samples#65]
RpcContext savedServerContext = RpcContext.getServerContext();
        future.whenComplete((v, t) -> {
            System.out.println(savedServerContext.getAttachment("server-key1"));
            if (t != null) {
                t.printStackTrace();
            } else {
                System.out.println("AsyncConsumer: Response: " + v);
            }
        });
savedServerContext.getAttachment("server-key1")返回null

**Comment by lizanle521** [comment]
有人么，感觉是2.7.0的大bug呀？

**Comment by kexianjun** [comment]
Pls refer to https://github.com/apache/incubator-dubbo/issues/3620
