### ISSUE TITLE
add dubbo-samples-consul demo

### ISSUE THREAD

**Issue by Moriadry** [apache/incubator-dubbo-samples#73]
add dubbo-samples-consul demo

**Comment by beiwei30** [comment]
@Moriadry I added a very basic consul demo: https://github.com/apache/incubator-dubbo-samples/tree/master/dubbo-samples-consul. Feel free to enhance. 

With this sample, the TCP check works as expected, pls. take a look.

**Comment by Moriadry** [comment]
@beiwei30  yes, I will take a look, thanks.

**Comment by beiwei30** [comment]
the only flaw of TCP check is: if there's no client connected, the provider will keep printing when consul send a TCP request to dubbo's port, which is quite annoying:

```
Apr 30, 2019 2:12:38 PM org.apache.dubbo.remoting.transport.AbstractServer warn
WARNING:  [DUBBO] All clients has disconnected from 0.0.0.0/0.0.0.0:20880. You can graceful shutdown now., dubbo version: 2.7.1, current host: 30.5.124.198
Apr 30, 2019 2:12:48 PM org.apache.dubbo.remoting.transport.AbstractServer warn
WARNING:  [DUBBO] All clients has disconnected from 0.0.0.0/0.0.0.0:20880. You can graceful shutdown now., dubbo version: 2.7.1, current host: 30.5.124.198
```

**Comment by Moriadry** [comment]
Hi Ian, it seems the sample works fine. I believe some code in ConsulRegistry.java went wrong, they don't work correctly with the TCP check. you can get correct response because you use the `subscribed` variable to get URL subscribed, rather than the msg from consul(not sure about this).

pls check this branch : https://github.com/Moriadry/incubator-dubbo/tree/feature/fordebug with this two different version of ConsulRegistry, and debug ConsulRegistryTest.testSubscribe locally, you will find the difference.

you can debug ConsulRegistryTest.testSubscribe.java, make a breakpoint at https://github.com/apache/incubator-dubbo/blob/e2f3346d9d1dff2bf6bf3ac2802e83d46b9923c0/dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java#L135
you will figure out we cannot get a NonEmpty HealthService list response returned. But with http-ttl Check, we can get correct HealthService list.

I believe our usage of TCP check is incorrect, we can spend more time on this to figure it out. I'm trying to fix it. I'm on my vocation those days,  so it needs a few days.

**Comment by Moriadry** [comment]
Or we can just use http ttl Check, those two checks are both the typical usage provided by consul.io, I believe their robustness can be consider mostly equal :)  In case we can't figure this out :(

**Comment by beiwei30** [comment]
@Moriadry pls. consider to create a http ttl check pull request, based on my previous change.

**Comment by beiwei30** [comment]
> pls check this branch : https://github.com/Moriadry/incubator-dubbo/tree/feature/fordebug with this two different version of ConsulRegistry, and debug ConsulRegistryTest.testSubscribe locally, you will find the difference.

> you can debug ConsulRegistryTest.testSubscribe.java, make a breakpoint at https://github.com/apache/incubator-dubbo/blob/e2f3346d9d1dff2bf6bf3ac2802e83d46b9923c0/dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java#L135
you will figure out we cannot get a NonEmpty HealthService list response returned. But with http-ttl Check, we can get correct HealthService list.

It this the exact change I have merged into the main trunk?

**Comment by beiwei30** [comment]
@Moriadry I checked your unit test, since you do not register any service in advanced, isn't it expected an empty list returned?

**Comment by Moriadry** [comment]
@beiwei30 With my uint test, if you use two different consulregistry(tcp and http), getHealthService will return different result(one is empty, one is not, when you register again). In your merged version, still use tcp, but lookup URL without setPassing(true).

Let me just create a http ttl check.

**Comment by moonlighf** [comment]
how to solve ` the provider will keep printing when consul send a TCP request to dubbo's port` and print `[DUBBO] All clients has disconnected from 0.0.0.0/0.0.0.0:20880.`
