### ISSUE TITLE
 dubbo-samples-api 这个readme.md是不是有问题的

### ISSUE THREAD

**Issue by mengxu2018** [apache/incubator-dubbo-samples#79]
https://github.com/apache/incubator-dubbo-samples/tree/master/dubbo-samples-api
这个里面client和server都是下面这样
mvn -Djava.net.preferIPv4Stack=true -Dexec.mainClass=Application exec:java
包名都没有的
然后我参考了这个文档
http://dubbo.apache.org/en-us/blog/dubbo-101.html
发现整个项目里面根本没有org.apache.dubbo.samples.provider.Application

**Comment by beiwei30** [comment]
this issue should be fixed with dd06c907e62f40a631d983c9f711edf051ce3807
